class CreateAddresses < ActiveRecord::Migration[5.2]
  def change
    create_table :addresses do |t|
      t.string :alleyCrossStreetsFlag
      t.string :assemblyDistrict
      t.string :bbl
      t.string :bblBoroughCode
      t.string :bblTaxBlock
      t.string :bblTaxLot
      t.string :boardOfElectionsPreferredLgc
      t.string :boePreferredStreetName
      t.string :boePreferredstreetCode
      t.string :buildingIdentificationNumber
      t.string :censusBlock2000
      t.string :censusBlock2010
      t.string :censusTract1990
      t.string :censusTract2000
      t.string :censusTract2010
      t.string :cityCouncilDistrict
      t.string :civilCourtDistrict
      t.string :coincidentSegmentCount
      t.string :communityDistrict
      t.string :communityDistrictBoroughCode
      t.string :communityDistrictNumber
      t.string :communitySchoolDistrict
      t.string :condominiumBillingBbl
      t.string :condominiumFlag
      t.string :congressionalDistrict
      t.string :cooperativeIdNumber
      t.string :crossStreetNamesFlagIn
      t.string :dcpPreferredLgc
      t.string :dofCondominiumIdentificationNumber
      t.string :dotStreetLightContractorArea
      t.string :dynamicBlock
      t.string :electionDistrict
      t.string :fireBattalion
      t.string :fireCompanyNumber
      t.string :fireCompanyType
      t.string :fireDivision
      t.string :firstBoroughName
      t.string :firstStreetCode
      t.string :firstStreetNameNormalized
      t.string :fromLionNodeId
      t.string :fromPreferredLgcsFirstSetOf5
      t.string :genericId
      t.string :geosupportFunctionCode
      t.string :geosupportReturnCode
      t.string :geosupportReturnCode2
      t.string :gi5DigitStreetCode1
      t.string :giBoroughCode1
      t.string :giBuildingIdentificationNumber1
      t.string :giDcpPreferredLgc1
      t.string :giHighHouseNumber1
      t.string :giLowHouseNumber1
      t.string :giSideOfStreetIndicator1
      t.string :giStreetCode1
      t.string :giStreetName1
      t.string :healthArea
      t.string :healthCenterDistrict
      t.string :highBblOfThisBuildingsCondominiumUnits
      t.string :highCrossStreetB5SC1
      t.string :highCrossStreetCode1
      t.string :highCrossStreetName1
      t.string :highHouseNumberOfBlockfaceSortFormat
      t.string :houseNumber
      t.string :houseNumberIn
      t.string :houseNumberSortFormat
      t.string :hurricaneEvacuationZone
      t.string :individualSegmentLength
      t.string :instructionalRegion
      t.string :interimAssistanceEligibilityIndicator
      t.string :internalLabelXCoordinate
      t.string :internalLabelYCoordinate
      t.float :latitude
      t.float :latitudeInternalLabel
      t.string :legacySegmentId
      t.string :lionBoroughCode
      t.string :lionBoroughCodeForVanityAddress
      t.string :lionFaceCode
      t.string :lionFaceCodeForVanityAddress
      t.string :lionKey
      t.string :lionKeyForVanityAddress
      t.string :lionSequenceNumber
      t.string :lionSequenceNumberForVanityAddress
      t.string :listOf4Lgcs
      t.float :longitude
      t.float :longitudeInternalLabel
      t.string :lowBblOfThisBuildingsCondominiumUnits
      t.string :lowCrossStreetB5SC1
      t.string :lowCrossStreetCode1
      t.string :lowCrossStreetName1
      t.string :lowHouseNumberOfBlockfaceSortFormat
      t.string :lowHouseNumberOfDefiningAddressRange
      t.string :noCrossStreetCalculationFlag
      t.string :nta
      t.string :ntaName
      t.string :numberOfCrossStreetB5SCsHighAddressEnd
      t.string :numberOfCrossStreetB5SCsLowAddressEnd
      t.string :numberOfCrossStreetsHighAddressEnd
      t.string :numberOfCrossStreetsLowAddressEnd
      t.string :numberOfEntriesInListOfGeographicIdentifiers
      t.string :numberOfExistingStructuresOnLot
      t.string :numberOfStreetFrontagesOfLot
      t.string :physicalId
      t.string :policePatrolBoroughCommand
      t.string :policePrecinct
      t.string :returnCode1a
      t.string :returnCode1e
      t.string :roadwayType
      t.string :rpadBuildingClassificationCode
      t.string :rpadSelfCheckCodeForBbl
      t.string :sanbornBoroughCode
      t.string :sanbornPageNumber
      t.string :sanbornVolumeNumber
      t.string :sanbornVolumeNumberSuffix
      t.string :sanitationCollectionSchedulingSectionAndSubsection
      t.string :sanitationDistrict
      t.string :sanitationRecyclingCollectionSchedule
      t.string :sanitationRegularCollectionSchedule
      t.string :sanitationSnowPriorityCode
      t.string :segmentAzimuth
      t.string :segmentIdentifier
      t.string :segmentLengthInFeet
      t.string :segmentOrientation
      t.string :segmentTypeCode
      t.string :selfCheckCodeOfBillingBbl
      t.string :sideOfStreetIndicator
      t.string :sideOfStreetOfVanityAddress
      t.string :splitLowHouseNumber
      t.string :stateSenatorialDistrict
      t.string :streetName1In
      t.string :streetStatus
      t.string :streetWidth
      t.string :taxMapNumberSectionAndVolume
      t.string :toLionNodeId
      t.string :toPreferredLgcsFirstSetOf5
      t.string :trafficDirection
      t.string :underlyingStreetCode
      t.string :uspsPreferredCityName
      t.string :workAreaFormatIndicatorIn
      t.string :xCoordinate
      t.string :xCoordinateHighAddressEnd
      t.string :xCoordinateLowAddressEnd
      t.string :xCoordinateOfCenterofCurvature
      t.string :yCoordinate
      t.string :yCoordinateHighAddressEnd
      t.string :yCoordinateLowAddressEnd
      t.string :yCoordinateOfCenterofCurvature
      t.string :zipCode
      t.string :zipCodeIn

      t.timestamps
    end
  end
end
